// Code generated by ogen, DO NOT EDIT.

package client

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// TokenAuth provides TokenAuth security value.
	TokenAuth(ctx context.Context, operationName OperationName) (TokenAuth, error)
}

func (s *Client) securityTokenAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.TokenAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"TokenAuth\"")
	}
	req.Header.Set("Authorization", t.APIKey)
	return nil
}
