// Code generated by ogen, DO NOT EDIT.
package client

type AddGalleryImageReq interface {
	addGalleryImageReq()
}

type AddGalleryImageRes interface {
	addGalleryImageRes()
}

type AddTeamMemberRes interface {
	addTeamMemberRes()
}

type ChangeProjectIconReq interface {
	changeProjectIconReq()
}

type ChangeProjectIconRes interface {
	changeProjectIconRes()
}

type ChangeUserIconReq interface {
	changeUserIconReq()
}

type ChangeUserIconRes interface {
	changeUserIconRes()
}

type CheckProjectValidityRes interface {
	checkProjectValidityRes()
}

type CreateVersionRes interface {
	createVersionRes()
}

type DeleteFileFromHashRes interface {
	deleteFileFromHashRes()
}

type DeleteGalleryImageRes interface {
	deleteGalleryImageRes()
}

type DeleteNotificationRes interface {
	deleteNotificationRes()
}

type DeleteNotificationsRes interface {
	deleteNotificationsRes()
}

type DeleteProjectIconRes interface {
	deleteProjectIconRes()
}

type DeleteProjectRes interface {
	deleteProjectRes()
}

type DeleteTeamMemberRes interface {
	deleteTeamMemberRes()
}

type DeleteThreadMessageRes interface {
	deleteThreadMessageRes()
}

type DeleteUserIconRes interface {
	deleteUserIconRes()
}

type DeleteVersionRes interface {
	deleteVersionRes()
}

type FollowProjectRes interface {
	followProjectRes()
}

type ForgeUpdatesRes interface {
	forgeUpdatesRes()
}

type GetDependenciesRes interface {
	getDependenciesRes()
}

type GetFollowedProjectsRes interface {
	getFollowedProjectsRes()
}

type GetLatestVersionFromHashRes interface {
	getLatestVersionFromHashRes()
}

type GetLatestVersionsFromHashesRes interface {
	getLatestVersionsFromHashesRes()
}

type GetNotificationRes interface {
	getNotificationRes()
}

type GetNotificationsRes interface {
	getNotificationsRes()
}

type GetOpenReportsRes interface {
	getOpenReportsRes()
}

type GetPayoutHistoryRes interface {
	getPayoutHistoryRes()
}

type GetProjectRes interface {
	getProjectRes()
}

type GetProjectTeamMembersRes interface {
	getProjectTeamMembersRes()
}

type GetProjectVersionsRes interface {
	getProjectVersionsRes()
}

type GetReportRes interface {
	getReportRes()
}

type GetReportsRes interface {
	getReportsRes()
}

type GetThreadRes interface {
	getThreadRes()
}

type GetThreadsRes interface {
	getThreadsRes()
}

type GetUserFromAuthRes interface {
	getUserFromAuthRes()
}

type GetUserNotificationsRes interface {
	getUserNotificationsRes()
}

type GetUserProjectsRes interface {
	getUserProjectsRes()
}

type GetUserRes interface {
	getUserRes()
}

type GetVersionFromIdOrNumberRes interface {
	getVersionFromIdOrNumberRes()
}

type GetVersionRes interface {
	getVersionRes()
}

type JoinTeamRes interface {
	joinTeamRes()
}

type LicenseTextRes interface {
	licenseTextRes()
}

type ModifyGalleryImageRes interface {
	modifyGalleryImageRes()
}

type ModifyProjectRes interface {
	modifyProjectRes()
}

type ModifyReportRes interface {
	modifyReportRes()
}

type ModifyTeamMemberRes interface {
	modifyTeamMemberRes()
}

type ModifyUserRes interface {
	modifyUserRes()
}

type ModifyVersionRes interface {
	modifyVersionRes()
}

type PatchProjectsRes interface {
	patchProjectsRes()
}

type RandomProjectsRes interface {
	randomProjectsRes()
}

type ReadNotificationRes interface {
	readNotificationRes()
}

type ReadNotificationsRes interface {
	readNotificationsRes()
}

type ScheduleProjectRes interface {
	scheduleProjectRes()
}

type ScheduleVersionRes interface {
	scheduleVersionRes()
}

type SearchProjectsRes interface {
	searchProjectsRes()
}

type SendThreadMessageRes interface {
	sendThreadMessageRes()
}

type SubmitReportRes interface {
	submitReportRes()
}

type TransferTeamOwnershipRes interface {
	transferTeamOwnershipRes()
}

type UnfollowProjectRes interface {
	unfollowProjectRes()
}

type VersionFromHashRes interface {
	versionFromHashRes()
}

type VersionsFromHashesRes interface {
	versionsFromHashesRes()
}

type WithdrawPayoutRes interface {
	withdrawPayoutRes()
}
